title:             Kiran BG
email:             kodeutility@gmail.com
description:       Portfolio & Tech Blog
author:            Kiran BG
baseurl:           ""
url:               "http://kodeutility.github.io"

# Social Profiles
twitter_username:  kodeutility
github_username:   kodeutility
facebook_username:
email_id: kodeutility@gmail.com
linkedin_username: kiran-bg-012371167
medium_username: kodeutility

# Build settings
markdown:          kramdown
theme: jekyll-theme-clean-blog
paginate:          5
paginate_path:     "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
